anchor_version = "0.29.0"
solana_version = "1.18.26"

[workspace]
members = [
    "fuzz",
    "stable-swap-anchor",
    "stable-swap-client",
    "stable-swap-math",
    "stable-swap-math/sim",
    "stable-swap-program/program"
]

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[programs.mainnet]
stable_swap = { address = "8h7HJug4hX3C6eQcda5darrsZ5g9RHUYoN7h1dKkA9Jf", path = "stable-swap-program/program/src/lib.rs" }

[programs.devnet]
stable_swap = { address = "8h7HJug4hX3C6eQcda5darrsZ5g9RHUYoN7h1dKkA9Jf", path = "stable-swap-program/program/src/lib.rs" }

[programs.testnet]
stable_swap = { address = "8h7HJug4hX3C6eQcda5darrsZ5g9RHUYoN7h1dKkA9Jf", path = "stable-swap-program/program/src/lib.rs" }

[programs.localnet]
stable_swap = { address = "8h7HJug4hX3C6eQcda5darrsZ5g9RHUYoN7h1dKkA9Jf", path = "stable-swap-program/program/src/lib.rs" }
